---
sudo: required

env:
  - distribution: centos
    version: 7
  - distribution: centos
    version: 6


services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/mklettner.graylog-collector ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook --sudo -v /etc/ansible/roles/mklettner.graylog-collector/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook --sudo -v /etc/ansible/roles/mklettner.graylog-collector/tests/test.yml'
  - 'sudo docker rm -f "$(cat ${container_id})"'
